const express = require('express');
const router = express.Router();
const { protect, authorize } = require('../middleware/authMiddleware');
const { createOrderFromCheckout, createPaymentSession, createPublicPaymentSession, createRazorpayOrder, createPublicRazorpayOrder, lookupGuestCheckoutAccount, getCheckoutSummary, getPublicCheckoutSummary, retryPayment, retryRazorpayPayment, verifyPayment, verifyRazorpayPayment, verifyPublicPayment, verifyPublicRazorpayPayment, getPaymentAttemptStatus, getMyPaymentAttemptStatus, getPublicPaymentAttemptStatus, handlePaymentWebhook, handleRazorpayWebhook, handleIciciReturn, handleIciciWebhook, handleIciciSettlementWebhook, getAdminOrders, getAdminPaymentHealth, getAdminOrderById, getMyOrders, getMyOrderByPaymentRef, updateOrderStatus, fetchAdminPaymentStatus, fetchMyPaymentStatus, deleteAdminOrder, deleteAdminPaymentAttempt, reconcileAdminPaymentAttempt, convertAdminPaymentAttemptToOrder, createAdminManualOrder, getAdminManualCoupons, getAdminManualPreview, validateRecoveryCoupon, validatePublicRecoveryCoupon, getAvailableCoupons, getPublicAvailableCoupons, getCustomerPopupData, getPublicPopupData, downloadMyInvoicePdf, downloadAdminInvoicePdf, sendAdminInvoiceCommunication, getOverdueShippedSummary, confirmDeliveryBySignedLink, downloadInvoiceBySignedLink } = require('../controllers/orderController');

router.post('/checkout', protect, createOrderFromCheckout);
router.post('/payment/session/public', createPublicPaymentSession);
router.post('/razorpay/order/public', createPublicRazorpayOrder);
router.post('/checkout/account-lookup', lookupGuestCheckoutAccount);
router.post('/payment/session', protect, createPaymentSession);
router.post('/razorpay/order', protect, createRazorpayOrder);
router.post('/summary/public', getPublicCheckoutSummary);
router.post('/summary', protect, getCheckoutSummary);
router.post('/coupon/validate/public', validatePublicRecoveryCoupon);
router.post('/coupon/validate', protect, validateRecoveryCoupon);
router.post('/coupons/available/public', getPublicAvailableCoupons);
router.get('/coupons/available', protect, getAvailableCoupons);
router.post('/coupons/available', protect, getAvailableCoupons);
router.get('/coupons/popup', protect, getCustomerPopupData);
router.get('/coupons/popup/public', getPublicPopupData);
router.post('/payment/retry', protect, retryPayment);
router.post('/razorpay/retry', protect, retryRazorpayPayment);
router.post('/payment/verify', protect, verifyPayment);
router.post('/razorpay/verify', protect, verifyRazorpayPayment);
router.post('/payment/verify/public', verifyPublicPayment);
router.post('/razorpay/verify/public', verifyPublicRazorpayPayment);
router.get('/payment/attempt/:id', protect, getPaymentAttemptStatus);
router.get('/razorpay/attempt/:id', protect, getMyPaymentAttemptStatus);
router.get('/razorpay/attempt/public/:id', getPublicPaymentAttemptStatus);
router.get('/payment/attempt/public/:id', getPublicPaymentAttemptStatus);
router.post('/payment/webhook', handlePaymentWebhook);
router.post('/razorpay/webhook', handleRazorpayWebhook);
router.post('/icici/return', handleIciciReturn);
router.post('/icici/webhook', handleIciciWebhook);
router.post('/icici/settlement-webhook', handleIciciSettlementWebhook);
router.get('/delivery/confirm', confirmDeliveryBySignedLink);
router.get('/invoice/share', downloadInvoiceBySignedLink);
router.get('/admin', protect, authorize('admin', 'staff'), getAdminOrders);
router.get('/admin/payment/health', protect, authorize('admin', 'staff'), getAdminPaymentHealth);
router.get('/admin/shipped/overdue-summary', protect, authorize('admin', 'staff'), getOverdueShippedSummary);
router.get('/admin/:id', protect, authorize('admin', 'staff'), getAdminOrderById);
router.put('/admin/:id/status', protect, authorize('admin', 'staff'), updateOrderStatus);
router.post('/admin/manual/coupons', protect, authorize('admin', 'staff'), getAdminManualCoupons);
router.post('/admin/manual/preview', protect, authorize('admin', 'staff'), getAdminManualPreview);
router.post('/admin/manual', protect, authorize('admin', 'staff'), createAdminManualOrder);
router.delete('/admin/:id', protect, authorize('admin', 'staff'), deleteAdminOrder);
router.delete('/admin/attempt/:id', protect, authorize('admin', 'staff'), deleteAdminPaymentAttempt);
router.post('/admin/attempt/:id/reconcile', protect, authorize('admin', 'staff'), reconcileAdminPaymentAttempt);
router.post('/admin/attempt/:id/convert', protect, authorize('admin', 'staff'), convertAdminPaymentAttemptToOrder);
router.post('/admin/payment/fetch-status', protect, authorize('admin', 'staff'), fetchAdminPaymentStatus);
router.get('/admin/:id/invoice', protect, authorize('admin', 'staff'), downloadAdminInvoicePdf);
router.post('/admin/:id/invoice/send', protect, authorize('admin', 'staff'), sendAdminInvoiceCommunication);
router.get('/my', protect, getMyOrders);
router.get('/my/payment/:paymentId', protect, getMyOrderByPaymentRef);
router.post('/my/payment/fetch-status', protect, fetchMyPaymentStatus);
router.get('/my/:id/invoice', protect, downloadMyInvoicePdf);

module.exports = router;
